# Generated by Django 4.0.1 on 2022-03-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=45)),
            ],
        ),
    ]
